### PR TITLE
Amass command update and notify arg parse bug fix

### PR DESCRIPTION
**Pull request by SbIm**
Amass command update and notify arg parse bug fix

### CODE REVIEW

**Comment by mzfr** [comment]
This PR will fix issue #45 & #44 right?

**Comment by SbIm** [comment]
> This PR will fix issue #45 & #44 right?

Yes.

**Comment by SbIm** [comment]
Fix 2 more bugs:
1. can't create *-all.txt
2. can't read csv file when using knockpy

**Comment by mzfr** [comment]
Thanks!!

**Pull request merged**
