### PR TITLE
Changed mode to 755 for domained.py

### PR DESCRIPTION
**Pull request by dainok**
I think could be useful having the main executable in 755.

### CODE REVIEW

**Comment by mzfr** [comment]
Hey,

Sorry for the very late reply :smile:, but can you please explain why would it be helpful to use 755?

**Comment by dainok** [comment]
I'm used to execute directly the scripts without calling the interpreter before, but... as you wish :)
I was including your repo in an Ansible script linking the main script into a custom bin directory and ... yadayadayada (lot of automation stuff).

**Comment by mzfr** [comment]
@ccsplit 	Any thoughts on this one?

**Comment by ccsplit** [comment]
Personally looks good to me, the only question I have is did you mean to commit the ThreatDragon file @dainok?

**Comment by dainok** [comment]
I changed only the permission. But as I wrote... no matter if you want to drop the change request.

**Comment by dainok** [comment]
Honestly I don’t know what is that for. I committed once 1 year ago, the following commits are just 3 months ago. Any CI/CD pipeline?

**Pull request closed without merging**
